# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d27874abc905f29ff2394ccb415c3df9"
name = "lan-trans"
handle = "lan-trans"
application_url = "https://enters-oecd-corpus-mini.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-xl.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,read_orders,read_products,read_script_tags,read_themes,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://enters-oecd-corpus-mini.trycloudflare.com/auth/callback",
  "https://enters-oecd-corpus-mini.trycloudflare.com/auth/shopify/callback",
  "https://enters-oecd-corpus-mini.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
